// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbidqdnocawybzhafjaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiaWRxZG5vY2F3eWJ6aGFmamF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDM3NTMsImV4cCI6MjA2NzA3OTc1M30.kbCE1xbW7fKfLYMo68ZSejjKvL_pXMBt147VCVwf1hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});